# Generated by Django 4.1 on 2024-07-27 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MusicApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='aduio_file',
            new_name='audio_file',
        ),
    ]
